spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
  devtools:
    livereload:
      enabled: true
  mustache:
    cache: false

server:
  servlet:
    encoding:
      force-response: true

